### ISSUE TITLE
Ugly README

### ISSUE THREAD

**Issue by cryatk** [METADIUM/go-metadium#1]
Hi there,
README is ugly, even it was just forked.
Why don't you keep consistency for wording?
Because of this, I am confused to start

#### Expected behaviour
In README.md, all wording about console should be `gmet` or `gmeta` or something

#### Actual behaviour
In README.md, `gmet`, `gmeth`, `geth` are mixed

#### Steps to reproduce the behaviour
Open README

**Comment by cryatk** [comment]
Nobody manage this repo? Passed 5  days.

**Comment by cryatk** [comment]
Wow 10 days have passed. Amazing repo. It seems like a scam.

**Comment by cryatk** [comment]
15 days... There is no doubt that it is scam. @sadoci don’t have any responsibility.

**Comment by MetadiumRelease** [comment]
Thanks for picking up typos. Fixed issues raised here, except `geth` is still used the original `go-ethereum` `README.md`.
