### ISSUE TITLE
Why fees and rewards are included in block and transaction?

### ISSUE THREAD

**Issue by cryatk** [METADIUM/go-metadium#2]
As [changes](https://github.com/ethereum/go-ethereum/compare/master...METADIUM:master),

Why `fees` and `rewards` are included in block and transaction through `core/types.go`,  `core/types/block.go` and so on.

What's the meaning of `fees`? I cannot understand why it is needed even if there is already gas.
What's the meaning of `rewards`? you cannot know how many people attested in mining.

There is no documentation and comments. It is one of the biggest change compared with go-ethereum. You should mention why.

**Comment by sadoci** [comment]
In Metadium, rewards (block reward + fees) are distributed according to stakes in the governance contract. Stakes in the previous block's governance contract are used. The exact way, including the exact block reward, is to be defined in governance contract. This is still in progress, if not obvious enough.

We believe this is necessary to satisfy our TPS requirement, at least several thousands per second.

**Comment by cryatk** [comment]
I mean why they are on platform code-level? not contract as protocol. Then block producer can manipulate reward amount for them. Authorities have too many permissions.

Still I’m curious about fees, should user pay fee with gas? and why it makes TPS faster? What is difference with fee and gas

**Comment by sadoci** [comment]
Fees = Sum(tx.gasUsed * tx.gasPrice) is not the same as block.gasUsed.

For faster TPS, Metadium has greater gas limits and generates blocks immediately, which means that number of blocks, hence total amount of block rewards per given duration is not bounded. Hence the need of controlling block reward, which comes from governance contract for now for more flexibility, at least during testnet period. 

If received block's fees and reward are incorrect, the block gets rejected.

In stock ethereum code, fees are awarded during evm execution, and block reward is awarded when a block gets in the chain. This model doesn't work with our reward model where reward (block reward + fees) is distributed among authorities according to stakes.

**Comment by cryatk** [comment]
Did you think I do not know fee equation? No, why did you do that even if ethereum don’t adopt

Explanation for TPS is totally unacceptable. Gas limit is just limit, not computing power bound. How will you solve the problem technically compared with others such as Plasma

**Comment by cryatk** [comment]
There is no more discussion lol. Amazing project and commiter @sadoci I cant believe
