### ISSUE TITLE
anybody working on this project anymore?

### ISSUE THREAD

**Issue by vbutern** [METADIUM/go-metadium#3]
Hi there,

please note that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use the gitter channel or the Ethereum stack exchange at https://ethereum.stackexchange.com.

#### System information

Geth version: `geth version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Backtrace

````
[backtrace]
````

**Comment by MetadiumRelease** [comment]
Sorry for the late response.
We are planning to start Metadium testnet at the end of September 2018.
Please stay tuned
